import { ERROR_CODES } from './../../enums/error-codes';
import { SDG } from 'src/app/enums/sdg';

const localization: { [token: string]: string } = {
  appName: 'Hear Me Now',
  'core.yes': 'Yes',
  'core.no': 'No',
  'core.confirm': 'Confirm',
  'core.cancel': 'cancel',
  'core.greeting': 'Hello {{user}}',
  'core.share': 'share',
  'core.votes': 'votes',
  'core.firstName': 'first name',
  'core.lastName': 'last name',
  'core.email': 'email',
  'core.number': 'phone number',
  'core.country': 'country',
  'core.zipCode': 'zip/postal code',
  'core.birthDate': 'birth date',
  'core.group': 'student Group',
  'core.password': 'password',
  'core.userStatus': 'user status',
  'core.authorType': 'User type',
  'core.authorType.admin': 'Admin',
  'core.authorType.teacher': 'Teacher',
  'core.authorType.student': 'Student',
  'core.delete': 'delete',
  'core.edit': 'edit',
  'core.close': 'close',
  'core.clear': 'clear',
  'core.vote.for': 'For',
  'core.vote.against': 'Against',
  'core.vote.abstain': 'Abstain',
  'core.emailToken': 'Security Code',
  'core.newPassword': 'new password',
  'core.confirmPassword': 'confirm password',
  'core.newInitiative': 'Create a new initiative',
  'core.noInitiatives': 'No initiatives found',
  'core.delete.item': 'Are you sure?',
  'core.delete.project':
    'Are you sure you want to delete initiative "{{title}}"?',
  'core.closed': 'closed',


  'lang.en': 'English',
  'lang.fr': 'French (Français)',
  'lang.kr': 'Korean (한국어)',

  [`sdg.${SDG.POVERTY}`]: 'No Poverty',
  [`sdg.${SDG.HUNGER}`]: 'Zero Hunger',
  [`sdg.${SDG.HEALTH}`]: 'Good Health & Well-Being',
  [`sdg.${SDG.EDUCATION}`]: 'Quality Education',
  [`sdg.${SDG.GENDER}`]: 'Gender Equality',
  [`sdg.${SDG.WATER}`]: 'Clean Water & Sanitation',
  [`sdg.${SDG.ENERGY}`]: 'Affordable & Clean Energy',
  [`sdg.${SDG.ECONOMIC}`]: 'Decent Work & Economic Growth',
  [`sdg.${SDG.INDUSTRY}`]: 'Industry, Innovation & Infrastructure',
  [`sdg.${SDG.INEQUALITIES}`]: 'Reduced Inequalities',
  [`sdg.${SDG.COMMUNITIES}`]: 'Sustainable Cities & Communities',
  [`sdg.${SDG.CONSUMPTION}`]: 'Responsible Consumption & Production',
  [`sdg.${SDG.CLIMATE}`]: 'Climate Action',
  [`sdg.${SDG.SEA_LIFE}`]: 'Life Below Water',
  [`sdg.${SDG.LAND_LIFE}`]: 'Life on Land',
  [`sdg.${SDG.PEACE}`]: 'Peace, Justice & Strong Institutions',
  [`sdg.${SDG.PARTNERSHIPS}`]: 'Partnerships For the Goals',
  [`sdg.${SDG._TRENDING}`]: 'Trending',
  [`sdg.${SDG._LOCAL}`]: 'Local to you',

  'pages.notFound.title': '404 page Not Found',
  'pages.notFound.wentWrong': 'Something went terribly wrong!',
  'pages.notFound.pageNotFound': 'The key to this page is lost!',

  'pages.signup.title': 'Create your HEAR ME NOW account now!',
  'pages.signup.tab.teacher': "I'm a teacher",
  'pages.signup.tab.student': "I'm a student",
  'pages.signup.tab.user': "I'm a user",
  'pages.signup.button.signup': 'sign up',
  'pages.signup.login': 'Already have an account',
  'pages.signup.success':
    'Account was successfully created.<br>Please check your emails for the confirmation email.',

  'pages.login.title': 'Login into your account',
  'pages.login.button.login': 'login',
  'pages.login.link.forgotPassword': 'forgot password?',
  'pages.login.link.newAccount': 'Create a new account',
  'pages.login.success': 'Logged In Successfully',
  'pages.login.error.credentials': 'Wrong credentials, please try again.',
  'pages.login.toast.logout': 'Logged out.',

  'pages.home.about.title': 'About',
  'pages.home.about.content': "The Hear Me Now operation gives the youth a chance to express their opinions on issues that matter to them and teach them that they can make a change in the world. The youth are the future of this world, and their point of view and vision will shape the future. Hear Me Now serves as a tool for the younger generation to express their ideas and make this world a better place. This platform allows students from different age groups to create their own initiatives and express their opinion by abstaining or voting for or against other initiatives. Moreover, this voting feature allows the youth to see their votes and consequent local or global impact in real-time.",
  'pages.home.sdg.title': 'SDG',
  'pages.home.sdg.content': 'The Sustainable Development Goals are a universal call to action to end poverty, protect the planet and improve the lives and prospects of everyone, everywhere. The 17 Goals were adopted by all UN Member States in 2015, as part of the 2030 Agenda for Sustainable Development which set out a 15-year plan to achieve the Goals.',
  [`pages.home.sdg.${SDG.POVERTY}`]: 'End poverty in all its forms everywhere.',
  [`pages.home.sdg.${SDG.HUNGER}`]: 'End hunger, achieve food security and improved nutrition and promote sustainable agriculture.',
  [`pages.home.sdg.${SDG.HEALTH}`]: 'Ensure healthy lives and promote well-being for all at all ages.',
  [`pages.home.sdg.${SDG.EDUCATION}`]: 'Ensure inclusive and equitable quality education and promote lifelong learning opportunities for all.',
  [`pages.home.sdg.${SDG.GENDER}`]: 'Achieve gender equality and empower all women and girls.',
  [`pages.home.sdg.${SDG.WATER}`]: 'Ensure availability and sustainable management of water and sanitation for all.',
  [`pages.home.sdg.${SDG.ENERGY}`]: 'Ensure access to affordable, reliable, sustainable and modern energy for all.',
  [`pages.home.sdg.${SDG.ECONOMIC}`]: 'Promote sustained, inclusive and sustainable economic growth, full and productive employment and decent work for all.',
  [`pages.home.sdg.${SDG.INDUSTRY}`]: 'Build resilient infrastructure, promote inclusive and sustainable industrialization and foster innovation.',
  [`pages.home.sdg.${SDG.INEQUALITIES}`]: 'Reduce inequality within and among countries.',
  [`pages.home.sdg.${SDG.COMMUNITIES}`]: 'Make cities and human settlements inclusive, safe, resilient and sustainable.',
  [`pages.home.sdg.${SDG.CONSUMPTION}`]: 'Ensure sustainable consumption and production patterns.',
  [`pages.home.sdg.${SDG.CLIMATE}`]: 'Take urgent action to combat climate change and its impacts.',
  [`pages.home.sdg.${SDG.SEA_LIFE}`]: 'Conserve and sustainably use the oceans, seas and marine resources for sustainable development.',
  [`pages.home.sdg.${SDG.LAND_LIFE}`]: 'Protect, restore and promote sustainable use of terrestrial ecosystems, sustainably manage forests, combat desertification, and halt and reverse land degradation and halt biodiversity loss.',
  [`pages.home.sdg.${SDG.PEACE}`]: 'Promote peaceful and inclusive societies for sustainable development, provide access to justice for all and build effective, accountable and inclusive institutions at all levels.',
  [`pages.home.sdg.${SDG.PARTNERSHIPS}`]: 'Strengthen the means of implementation and revitalize the Global Partnership for Sustainable Development.',
  'pages.home.project.title': 'Initiatives',
  'pages.home.project.link.discover': 'discover initiatives',
  'pages.home.project.link.create': 'create an initiative',
  'pages.home.project.content': 'More than just a voting app, Hear Me Now allows youth to initiate projects, vote for open initiatives, and invite friends, schoolmates, and organizations. Further, sponsors can multiply their impact and voice. The consensus and majority votes will be presented to governments and corporations as the informed voice of the next generation.',

  'pages.discover.title': 'Discover',
  'pages.discover.loading.projects': 'Loading initiatives ...',
  'pages.discover.init.title': 'your initiatives',
  'pages.discover.loading': 'Loading initiatives',

  'pages.search.text': 'Text Query',
  'pages.search.text.error': 'Text query should at least be 3 characters',
  'pages.search.country': 'Country',
  'pages.search.country.error': 'Country name should at least be 2 characters',
  'pages.search.sdg': 'SDG',
  'pages.search.search': 'Search',

  'pages.profile.button.editProfile': 'Edit Profile',
  'pages.profile.button.changePhoto': 'Change photo',
  'pages.profile.button.changePassword': 'Change Password',
  'pages.profile.button.changeEmail': 'Change Email',
  'pages.profile.button.logout': 'Logout',
  'pages.profile.button.admin': 'Admin',
  'pages.profile.update.profile': 'Profile updated.',

  'pages.profileEdit.title': 'Edit Profile',
  'pages.profileEdit.button.save': 'Save',
  'pages.profileEdit.button.changeProfilePhoto': 'Change profile photo',

  'pages.favorite.title': 'Favorites & Votes',
  'pages.favorite.favorite': 'Favorite',
  'pages.favorite.added': 'Initiative has been added to the favorite list.',
  'pages.favorite.removed':
    'Initiative has been removed from the favorite list.',

  'pages.forgotPassword.title': 'Forgot Password',
  'pages.forgotPassword.success': 'Please check your email for a token.',
  'pages.forgotPassword.button.forgotPassword': 'next',

  'pages.resetPassword.title': 'Reset Password',
  'pages.resetPassword.success': 'Your password has been updated.',
  'pages.resetPassword.button.resetPassword': 'update password',

  'pages.changePassword.title': 'Change Password',
  'pages.changePassword.button.changePassword': 'update password',

  'pages.confirmEmail.title': 'Confirm Email Address',
  'pages.confirmEmail.header': 'A security code has been sent to "{{email}}".',
  'pages.confirmEmail.button.confirm': 'Confirm',
  'pages.confirmEmail.button.resend': 'Resend Code',
  'pages.confirmEmail.button.logout': 'Logout',
  'pages.confirmEmail.confirmed': 'Your email address has been confirmed.',
  'pages.confirmEmail.resend': 'a new code has been sent to your email.',

  'pages.updateEmail.title': 'Update Email',
  'pages.updateEmail.success': 'Security code has been sent to your email.',
  'pages.updateEmail.email': 'New Email',
  'pages.updateEmail.button.updateEmail': 'update',

  'pages.project.header.new.title': 'Creating initiative: ',
  'pages.project.header.edit.title': 'Editing initiative: ',
  'pages.project.submit.edit': 'update initiative',
  'pages.project.submit.new': 'create initiative',
  'pages.project.title': 'Title',
  'pages.project.subtitle': 'subtitle',
  'pages.project.images': 'images',
  'pages.project.description': 'description',
  'pages.project.impactStatement': 'impact statement',
  'pages.project.abstract': 'abstract',
  'pages.project.userid': 'Created By',
  'pages.project.sdg': 'Sustainable Development Goals',
  'pages.project.country': 'country',
  'pages.project.openDate': 'open date',
  'pages.project.closeDate': 'close date',
  'pages.project.isSponsored': 'is initiative sponsored',
  'pages.project.created': 'Your initiative have been successfully created',
  'pages.project.updated': 'Your initiative have been successfully updated',
  'pages.project.deleted': 'Your initiative have been deleted',
  'pages.images.add': 'Add new image',
  'pages.images.uploaded': 'Image was uploaded',
  'pages.images.removed': 'Image was removed',

  'pages.admin.header': 'Admin: Restricted access only',
  'pages.admin.titles.reports': 'reports',
  'pages.admin.titles.users': 'users',
  'pages.admin.titles.projects': 'projects',
  'pages.admin.empty.reports': 'no reports',
  'pages.admin.status.ban': 'ban',
  'pages.admin.status.unBan': 'un-ban',
  'pages.admin.status.submissionDate': 'Date of Submission',
  'pages.admin.status.reporter': 'Reporter',
  'pages.admin.delete.report': 'Report has been deleted',

  'pages.projectDetail.abstract': 'Abstract',
  'pages.projectDetail.impact': 'Impact Statement',
  'pages.projectDetail.aboutInitiative': 'About Initiative',
  'pages.projectDetail.readMore': 'Read More',
  'pages.projectDetail.readLess': 'Read Less',
  'pages.projectDetail.alreadyVoted': 'Already Voted',
  'pages.projectDetail.voted': 'Your votes has been submitted',
  'pages.projectDetail.sdg': 'Sdg',
  'pages.projectDetail.youth': 'youth',
  'pages.projectDetail.voices': 'voices',
  'pages.projectDetail.report': 'Report',
  'pages.projectDetail.reported': 'Project has been Reported.',
  'pages.projectDetail.share': 'Copy Link',
  'pages.projectDetail.share.copied':
    'Initiative link has been copied to your clipboard.',
  'pages.projectDetail.cancel': 'Cancel',
  'pages.projectDetail.ellipsis': '...',

  'pages.admin.user.update': 'Update User',
  'pages.admin.user.title': 'Admin User Edit',
  'pages.admin.user.banned': 'User is banned.',
  'pages.admin.user.unbanned': 'User is unbanned',
  'pages.admin.user.deleted': 'User has been deleted.',

  'reports.message.guidelines': 'Against community guidelines',
  'pages.projectVote.vote': 'Vote',
  'pages.projectVote.closeDate': 'Close Date:',
  'pages.projectVote.voteToChange': "Let's vote to change it",

  'errors.field.fixIt': 'Please resolve all the errors and try again.',
  'errors.field.requiredImage': 'You need at least one image.',
  'errors.field.required': 'Required field',
  'errors.field.limit': 'Field should be between {{min}} and {{max}}',
  'errors.field.maxLimit': 'Field can not be longer than {{max}}',
  'errors.field.minLimit': 'Field can not be shorter than {{min}}',
  'errors.field.invalid': 'Invalid {{name}} value.',
  'errors.field.invalid.email': 'Invalid email format',
  'errors.field.invalid.group': 'Invalid group name',
  'errors.field.emailToken.onlyNumbersRequired': 'Only numbers required',
  'errors.field.sdg.max': 'Can not select more than 3 goals.',
  'errors.field.password.notMatch': 'Passwords do not match',
  'errors.field.password.week': 'Password is too weak.',
  'errors.field.password.should.length':
    'Password should at least be 8 characters.',
  'errors.field.password.should.upper':
    'Password should have upper case letters.',
  'errors.field.password.should.lower':
    'Password should have lower case letters.',
  'errors.field.password.should.number': 'Password should have numerals.',
  'errors.field.password.should.special':
    'Password should have special character.',
  'errors.http.unknown': 'Something went wrong :(',
  [`errors.http.${ERROR_CODES.UNEXPECTED_ERROR}`]: 'Something went wrong :(',
  [`errors.http.${ERROR_CODES.BAD_REQUEST}`]: 'Invalid request!',
  [`errors.http.${ERROR_CODES.NOT_AUTHENTICATED}`]: 'Authentication failed!',
  [`errors.http.${ERROR_CODES.NOT_FOUND}`]:
    'Could not find the requested item.',
  [`errors.http.${ERROR_CODES.NOT_AUTHORIZED}`]: 'Action not authorized!',
  [`errors.http.${ERROR_CODES.INVALID_CREDENTIALS}`]:
    'Email or password is invalid!',
  [`errors.http.${ERROR_CODES.PROJECT_ALREADY_FAVORITED}`]:
    'Project is already in user favorites!',
  [`errors.http.${ERROR_CODES.ACCOUNT_ALREADY_EXISTS}`]:
    'The entered email is already associated with an account!',
  [`errors.http.${ERROR_CODES.PROJECT_NOT_FOUND}`]:
    'Could not find the initiative!',
  [`errors.http.${ERROR_CODES.IMAGE_REMOVE}`]: 'Could not remove the image!',
  [`errors.http.${ERROR_CODES.IMAGE_UPLOAD}`]: 'Could not upload the image!',
  [`errors.http.${ERROR_CODES.BANNED}`]:
    'Your account is banned by admin, please contact support.',
  [`errors.http.${ERROR_CODES.PROJECT_ALREADY_VOTED}`]:
    'You have already used this voting option for this initiative',
  [`errors.http.${ERROR_CODES.INVALID_GROUP}`]: 'Entered group does not exist',
};

export default localization;
